"""alter users table, and alter table catalogs and tags fullname to username

Revision ID: 05d2543fe07c
Revises: 3ca0e7702af0
Create Date: 2020-02-29 14:09:02.710118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05d2543fe07c'
down_revision = '3ca0e7702af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False, comment='評書人'))
        batch_op.drop_column('fullname')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False, comment='留言者'))
        batch_op.drop_column('fullname')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False, comment='留言者'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='建立時間'))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False, comment='信箱'))
        batch_op.add_column(sa.Column('fullname', sa.String(length=80), nullable=False, comment='本名'))
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', mysql.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('fullname')
        batch_op.drop_column('email')
        batch_op.drop_column('createdAt')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('username')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', mysql.VARCHAR(length=100), nullable=False, comment='留言者'))
        batch_op.drop_column('username')

    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', mysql.VARCHAR(length=50), nullable=False, comment='評書人'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
