"""Create new tables

Revision ID: 166aa952a668
Revises: 
Create Date: 2020-01-31 00:07:49.384727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '166aa952a668'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=1),
               existing_comment='評分',
               existing_nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=1),
               existing_comment='評分',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.Float(precision=1),
               type_=mysql.FLOAT(),
               existing_comment='評分',
               existing_nullable=True)

    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.Float(precision=1),
               type_=mysql.FLOAT(),
               existing_comment='評分',
               existing_nullable=True)

    # ### end Alembic commands ###
