"""alter tables catalogs and comments change column review DECIMAL(2,1)

Revision ID: 3ca0e7702af0
Revises: 63c6cb4fe25b
Create Date: 2020-02-01 19:22:54.466584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ca0e7702af0'
down_revision = '63c6cb4fe25b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=2, scale=1),
               existing_comment='評分',
               existing_nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=2, scale=1),
               existing_comment='評分',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.DECIMAL(precision=2, scale=1),
               type_=mysql.FLOAT(),
               existing_comment='評分',
               existing_nullable=True)

    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.DECIMAL(precision=2, scale=1),
               type_=mysql.FLOAT(),
               existing_comment='評分',
               existing_nullable=True)

    # ### end Alembic commands ###
