"""delete table tags_catalogs createdAt and updatedAt

Revision ID: 81e32fdef174
Revises: 2921d544a928
Create Date: 2020-03-02 00:24:53.610851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e32fdef174'
down_revision = '2921d544a928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags_catalogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='建立時間'))
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags_catalogs', schema=None) as batch_op:
        batch_op.drop_column('updatedAt')
        batch_op.drop_column('createdAt')

    # ### end Alembic commands ###
