"""add new column updateAt in tables comments and tags 

Revision ID: 8d6527111230
Revises: c3b61f0e1d76
Create Date: 2020-02-01 18:54:03.226162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d6527111230'
down_revision = 'c3b61f0e1d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=1),
               existing_comment='評分',
               existing_nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'))
        batch_op.alter_column('createdAt',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='建立時間',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('review',
               existing_type=mysql.FLOAT(),
               type_=sa.Float(precision=1),
               existing_comment='評分',
               existing_nullable=True)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新時間'))
        batch_op.alter_column('createdAt',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='建立時間',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('createdAt',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='建立時間',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('updatedAt')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.Float(precision=1),
               type_=mysql.FLOAT(),
               existing_comment='評分',
               existing_nullable=True)
        batch_op.alter_column('createdAt',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='建立時間',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('updatedAt')

    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.Float(precision=1),
               type_=mysql.FLOAT(),
               existing_comment='評分',
               existing_nullable=True)

    # ### end Alembic commands ###
