"""users' password don't unique

Revision ID: af1ae124ad2b
Revises: 0b14f72d1b25
Create Date: 2020-02-29 14:21:53.445650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1ae124ad2b'
down_revision = '0b14f72d1b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('password', ['password'], unique=True)

    # ### end Alembic commands ###
